import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header className="flex items-center justify-between px-6 py-2 bg-[#F5F0E5]">
        <div className="flex items-center space-x-4">
          <Image src="/images/wordem-icon-edited.png" alt="WordEm logo" width={50} height={50} />
          <Link href="/" className="text-2xl font-bold text-[#009963]">WordEm</Link>
        </div>
        <nav>
          <ul className="flex space-x-4">
            <li className="flex justify-center items-center"><Link href="/" className="hover:underline text-[#009963]">Home</Link></li>
            <li className="flex justify-center items-center"><Link href="/blog" className="hover:underline text-[#009963]">Blog</Link></li>
          </ul>
        </nav>
      </header>
      {children}
      <footer className="bg-[#F5F0E5] text-[#009963] py-6 px-6 text-center">
        <p>© 2024 WordEm. All rights reserved.</p> 
      </footer>
      </body>
    </html>
  );
}
